In [1]:
import pandas as pd
import numpy as np
import keras
import os

In [2]:
for dirpath, subdirs, files in os.walk(os.getcwd() + "\\train"):
    print(len(files))
    

229


In [3]:
train_dataset = np.ones((229,100,4))

In [4]:
for dirpath, subdirs, files in os.walk(os.getcwd() + "\\train"):
    for i,file in enumerate(files):
        print(dirpath + "\\"+ file)
        current_dataset = pd.read_csv(dirpath + "\\"+ file, header=0)
        train_dataset[i,:][:100] = current_dataset.iloc[:100,:].values
        print(len(current_dataset))
        #print(train_dataset[i,:192])

C:\Users\koste\NLP\train\chorale_000.csv
192
C:\Users\koste\NLP\train\chorale_001.csv
228
C:\Users\koste\NLP\train\chorale_002.csv
208
C:\Users\koste\NLP\train\chorale_003.csv
432
C:\Users\koste\NLP\train\chorale_004.csv
260
C:\Users\koste\NLP\train\chorale_005.csv
212
C:\Users\koste\NLP\train\chorale_006.csv
292
C:\Users\koste\NLP\train\chorale_007.csv
180
C:\Users\koste\NLP\train\chorale_008.csv
132
C:\Users\koste\NLP\train\chorale_009.csv
192
C:\Users\koste\NLP\train\chorale_010.csv
208
C:\Users\koste\NLP\train\chorale_011.csv
272
C:\Users\koste\NLP\train\chorale_012.csv
260
C:\Users\koste\NLP\train\chorale_013.csv
132
C:\Users\koste\NLP\train\chorale_014.csv
196
C:\Users\koste\NLP\train\chorale_015.csv
456
C:\Users\koste\NLP\train\chorale_016.csv
208
C:\Users\koste\NLP\train\chorale_017.csv
452
C:\Users\koste\NLP\train\chorale_018.csv
352
C:\Users\koste\NLP\train\chorale_019.csv
196
C:\Users\koste\NLP\train\chorale_020.csv
196
C:\Users\koste\NLP\train\chorale_021.csv
224
C:\Users\k

196
C:\Users\koste\NLP\train\chorale_198.csv
180
C:\Users\koste\NLP\train\chorale_199.csv
196
C:\Users\koste\NLP\train\chorale_200.csv
260
C:\Users\koste\NLP\train\chorale_201.csv
304
C:\Users\koste\NLP\train\chorale_202.csv
196
C:\Users\koste\NLP\train\chorale_203.csv
164
C:\Users\koste\NLP\train\chorale_204.csv
164
C:\Users\koste\NLP\train\chorale_205.csv
228
C:\Users\koste\NLP\train\chorale_206.csv
244
C:\Users\koste\NLP\train\chorale_207.csv
164
C:\Users\koste\NLP\train\chorale_208.csv
212
C:\Users\koste\NLP\train\chorale_209.csv
356
C:\Users\koste\NLP\train\chorale_210.csv
132
C:\Users\koste\NLP\train\chorale_211.csv
256
C:\Users\koste\NLP\train\chorale_212.csv
384
C:\Users\koste\NLP\train\chorale_213.csv
228
C:\Users\koste\NLP\train\chorale_214.csv
256
C:\Users\koste\NLP\train\chorale_215.csv
228
C:\Users\koste\NLP\train\chorale_216.csv
192
C:\Users\koste\NLP\train\chorale_217.csv
304
C:\Users\koste\NLP\train\chorale_218.csv
132
C:\Users\koste\NLP\train\chorale_219.csv
196
C:\Use

In [5]:
X_train = train_dataset.reshape((-1,1,4))[::2, :].copy()
Y_train = train_dataset.reshape((-1,1,4))[1::2, :].copy()

In [6]:
train_dataset.shape

(229, 100, 4)

In [59]:
X_train = train_dataset.reshape((-1,1,4))[::2, :].copy()
Y_train = train_dataset.reshape((-1,1,4))[1::2, :].copy()

In [60]:
X_train

array([[[74., 70., 65., 58.]],

       [[74., 70., 65., 58.]],

       [[75., 70., 58., 55.]],

       ...,

       [[64., 59., 56., 52.]],

       [[64., 61., 57., 57.]],

       [[64., 63., 54., 57.]]])

In [61]:
Y_train

array([[[74., 70., 65., 58.]],

       [[74., 70., 65., 58.]],

       [[75., 70., 58., 55.]],

       ...,

       [[64., 59., 56., 52.]],

       [[64., 61., 57., 57.]],

       [[64., 63., 54., 57.]]])

In [65]:
model = keras.models.Sequential([
    keras.layers.LSTM(20,return_sequences=True, input_shape=[None,4], recurrent_dropout=0.1),
    keras.layers.LSTM(20,return_sequences=True),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(4, activation="relu")
])
opt = keras.optimizers.Adam(lr=0.1)
model.compile(loss="categorical_crossentropy", optimizer=opt, metrics=['mse'])
history = model.fit(X_train, Y_train, epochs=6, batch_size=5, shuffle=True)

Epoch 1/6
2290/2290 [==============================] - 20s 8ms/step - loss: 346.1696 - mse: 3248.2795
Epoch 2/6
2290/2290 [==============================] - 17s 8ms/step - loss: 339.0191 - mse: 3225.7031
Epoch 3/6
2290/2290 [==============================] - 17s 8ms/step - loss: 339.0201 - mse: 2927.4626
Epoch 4/6
2290/2290 [==============================] - 17s 8ms/step - loss: 339.0188 - mse: 2370.0291
Epoch 5/6
2290/2290 [==============================] - 18s 8ms/step - loss: 339.0154 - mse: 1778.0236
Epoch 6/6
2290/2290 [==============================] - 18s 8ms/step - loss: 339.0115 - mse: 1274.5707


In [44]:
model.summary()

Model: "sequential_14"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_28 (LSTM)               (None, None, 20)          2960      
_________________________________________________________________
lstm_29 (LSTM)               (None, None, 20)          3280      
_________________________________________________________________
dropout_20 (Dropout)         (None, None, 20)          0         
_________________________________________________________________
dense_14 (Dense)             (None, None, 4)           84        
Total params: 6,324
Trainable params: 6,324
Non-trainable params: 0
_________________________________________________________________


In [66]:
model.predict(X_train[100:101,:])

array([[[34.34739 , 31.917343, 29.041132, 24.684526]]], dtype=float32)

In [67]:

n_notes = 10

generated_symphony = np.array(np.ones((n_notes,1,4)))

start_input = np.array([[[14.,54., 23., 43.]]])

previous_output = None

for i in range(n_notes):
    if i == 0:
        previous_output =  np.array(start_input)
    else:
        previous_output = model.predict(previous_output)
    print( np.array(model.predict(X_train[100:101,:]).reshape(1,4)))
    


[[34.34739  31.917343 29.041132 24.684526]]
[[34.34739  31.917343 29.041132 24.684526]]
[[34.34739  31.917343 29.041132 24.684526]]
[[34.34739  31.917343 29.041132 24.684526]]
[[34.34739  31.917343 29.041132 24.684526]]
[[34.34739  31.917343 29.041132 24.684526]]
[[34.34739  31.917343 29.041132 24.684526]]
[[34.34739  31.917343 29.041132 24.684526]]
[[34.34739  31.917343 29.041132 24.684526]]
[[34.34739  31.917343 29.041132 24.684526]]


In [ ]:
model = keras.models.Sequential()

model.add(keras.layers.InputLayer(input_shape=[None, 4]))

for rate in (1, 2, 4, 8) * 2:
    model.add(keras.layers.Conv1D(filters=20, kernel_size = 2, padding = "causal", activation="relu", dilation_rate=rate))
model.add(keras.layers.Conv1D(filters=10, kernel_size=1))          
model.add(keras.layers.Conv1D(filters=10, kernel_size=1))
model.add(keras.layers.Flatten())

model.add(keras.layers.Dense(4, activation="relu", input_shape=10))
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=['accuracy'])
history = model.fit(X_train, Y_train, epochs=20)